/**
 * Note: This file was auto-generated by TI PinMux on 10/11/2021.
 *
 * \file   J721S2_pinmux.h
 *
 * \brief  This file contains pad configure register offsets and bit-field 
 *         value macros for different configurations,
 *
 *           BIT[21]		TXDISABLE		disable the pin's output driver
 *           BIT[18]		RXACTIVE		enable the pin's input buffer (typically kept enabled)
 *           BIT[17]		PULLTYPESEL		set the iternal resistor pull direction high or low (if enabled)
 *           BIT[16]		PULLUDEN		internal resistor disable (0 = enabled / 1 = disabled)
 *           BIT[3:0]		MUXMODE			select the desired function on the given pin
 *
 *  \copyright Copyright (CU) 2021 Texas Instruments Incorporated - 
 *             http://www.ti.com/
 */

#ifndef _J7AEP_PIN_MUX_H_
#define _J7AEP_PIN_MUX_H_

/* ========================================================================== */
/*                             Include Files                                  */
/* ========================================================================== */

#include "ti/board/src/j721s2_evm/include/pinmux.h"
#include "ti/csl/csl_types.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ========================================================================== */
/*                           Macros & Typedefs                                */
/* ========================================================================== */
#define PIN_MODE(mode)	                (mode)
#define PINMUX_END                      (-1)

/** \brief Active mode configurations */
/** \brief Resistor enable */
#define PIN_PULL_DISABLE                (0x1U << 16U)
/** \brief Pull direction */
#define	PIN_PULL_DIRECTION              (0x1U << 17U)
/** \brief Receiver enable */
#define	PIN_INPUT_ENABLE                (0x1U << 18U)
/** \brief Driver disable */
#define	PIN_OUTPUT_DISABLE              (0x1U << 21U)
/** \brief Wakeup enable */
#define	PIN_WAKEUP_ENABLE               (0x1U << 29U)

/** \brief Pad config register offset in control module */

enum pinMainOffsets
{
	PIN_MCASP1_AXR0		 = 0xC0C0,
	PIN_MCASP1_AFSX		 = 0xC0BC,
	PIN_MCASP1_ACLKX		 = 0xC0B8,
	PIN_MCASP0_AXR12		 = 0xC0A0,
	PIN_MCASP0_AXR13		 = 0xC0A4,
	PIN_MCASP0_AXR14		 = 0xC0A8,
	PIN_MCASP1_AXR3		 = 0xC0B0,
	PIN_MCASP0_AXR15		 = 0xC0AC,
	PIN_MCASP0_AXR7		 = 0xC08C,
	PIN_MCASP0_AXR8		 = 0xC090,
	PIN_MCASP0_AXR9		 = 0xC094,
	PIN_MCASP0_AXR10		 = 0xC098,
	PIN_MCASP1_AXR4		 = 0xC0B4,
	PIN_MCASP0_AXR11		 = 0xC09C,
	PIN_TMS		 = 0xC11C,
	PIN_MCAN13_TX		 = 0xC00C,
	PIN_MCAN15_RX		 = 0xC020,
	PIN_GPIO0_11		 = 0xC02C,
	PIN_PMIC_WAKE0		 = 0xC034,
	PIN_MCASP0_AXR2		 = 0xC048,
	PIN_MCASP2_AXR0		 = 0xC05C,
	PIN_MCAN0_RX		 = 0xC068,
	PIN_MCAN1_RX		 = 0xC070,
	PIN_SPI0_CS0		 = 0xC0CC,
	PIN_I2C0_SCL		 = 0xC0E0,
	PIN_I2C0_SDA		 = 0xC0E4,
	PIN_ECAP0_IN_APWM_OUT		 = 0xC0C4,
	PIN_EXT_REFCLK1		 = 0xC0C8,
	PIN_MCAN0_TX		 = 0xC064,
	PIN_MCASP2_AXR1		 = 0xC060,
	PIN_MCAN14_TX		 = 0xC014,
	PIN_MCAN13_RX		 = 0xC010,
	PIN_MCAN15_TX		 = 0xC01C,
	PIN_MCAN14_RX		 = 0xC018,
	PIN_MCAN16_RX		 = 0xC028,
	PIN_MCAN16_TX		 = 0xC024,
	PIN_MMC1_CLK		 = 0xC104,
	PIN_MMC1_CMD		 = 0xC108,
	PIN_MMC1_DAT0		 = 0xC0FC,
	PIN_MMC1_DAT1		 = 0xC0F8,
	PIN_MMC1_DAT2		 = 0xC0F4,
	PIN_MMC1_DAT3		 = 0xC0F0,
	PIN_TIMER_IO0		 = 0xC0E8,
	PIN_WKUP_GPIO0_10		 = 0xC0E8,
	PIN_EXTINTN		 = 0xC000,
	PIN_RESETSTATZ		 = 0xC10C,
	PIN_SOC_SAFETY_ERRORN		 = 0xC110,
	PIN_MCASP0_AXR0		 = 0xC040,
	PIN_MCASP0_AXR1		 = 0xC044,
	PIN_SPI0_CS1		 = 0xC0D0,
	PIN_SPI0_CLK		 = 0xC0D4,
	PIN_SPI0_D0		 = 0xC0D8,
	PIN_SPI0_D1		 = 0xC0DC,
	PIN_MCAN12_RX		 = 0xC008,
	PIN_MCAN12_TX		 = 0xC004,
	PIN_TIMER_IO1		 = 0xC0EC,
};

enum pinWkupOffsets
{
	PIN_EMU0		 = 0xC12C,
	PIN_EMU1		 = 0xC130,
	PIN_TCK		 = 0xC124,
	PIN_TDI		 = 0xC114,
	PIN_TDO		 = 0xC118,
	PIN_TRSTN		 = 0xC128,
	PIN_MCU_ADC0_AIN0		 = 0xC134,
	PIN_MCU_ADC0_AIN1		 = 0xC138,
	PIN_MCU_ADC0_AIN2		 = 0xC13C,
	PIN_MCU_ADC0_AIN3		 = 0xC140,
	PIN_MCU_ADC0_AIN4		 = 0xC144,
	PIN_MCU_ADC0_AIN5		 = 0xC148,
	PIN_MCU_ADC0_AIN6		 = 0xC14C,
	PIN_MCU_ADC0_AIN7		 = 0xC150,
	PIN_MCU_ADC1_AIN0		 = 0xC154,
	PIN_MCU_ADC1_AIN1		 = 0xC158,
	PIN_MCU_ADC1_AIN2		 = 0xC15C,
	PIN_MCU_ADC1_AIN3		 = 0xC160,
	PIN_MCU_ADC1_AIN4		 = 0xC164,
	PIN_MCU_ADC1_AIN5		 = 0xC168,
	PIN_MCU_ADC1_AIN6		 = 0xC16C,
	PIN_MCU_ADC1_AIN7		 = 0xC170,
	PIN_MCU_RGMII1_RD0		 = 0xC094,
	PIN_MCU_RGMII1_RD1		 = 0xC090,
	PIN_MCU_RGMII1_RD2		 = 0xC08C,
	PIN_MCU_RGMII1_RD3		 = 0xC088,
	PIN_MCU_RGMII1_RXC		 = 0xC084,
	PIN_MCU_RGMII1_RX_CTL		 = 0xC06C,
	PIN_MCU_RGMII1_TD0		 = 0xC07C,
	PIN_MCU_RGMII1_TD1		 = 0xC078,
	PIN_MCU_RGMII1_TD2		 = 0xC074,
	PIN_MCU_RGMII1_TD3		 = 0xC070,
	PIN_MCU_RGMII1_TXC		 = 0xC080,
	PIN_MCU_RGMII1_TX_CTL		 = 0xC068,
	PIN_MCU_I2C0_SCL		 = 0xC108,
	PIN_MCU_I2C0_SDA		 = 0xC10C,
	PIN_WKUP_GPIO0_8		 = 0xC0E0,
	PIN_WKUP_GPIO0_9		 = 0xC0E4,
	PIN_WKUP_GPIO0_11		 = 0xC0EC,
	PIN_MCU_MCAN0_RX		 = 0xC0BC,
	PIN_MCU_MCAN0_TX		 = 0xC0B8,
	PIN_WKUP_GPIO0_5		 = 0xC0D4,
	PIN_WKUP_GPIO0_4		 = 0xC0D0,
	PIN_MCU_MDIO0_MDC		 = 0xC09C,
	PIN_MCU_MDIO0_MDIO		 = 0xC098,
	PIN_MCU_OSPI0_CLK		 = 0xC000,
	PIN_MCU_OSPI0_CSN0		 = 0xC02C,
	PIN_MCU_OSPI0_D0		 = 0xC00C,
	PIN_MCU_OSPI0_D1		 = 0xC010,
	PIN_MCU_OSPI0_D2		 = 0xC014,
	PIN_MCU_OSPI0_D3		 = 0xC018,
	PIN_MCU_OSPI0_D4		 = 0xC01C,
	PIN_MCU_OSPI0_D5		 = 0xC020,
	PIN_MCU_OSPI0_D6		 = 0xC024,
	PIN_MCU_OSPI0_D7		 = 0xC028,
	PIN_MCU_OSPI0_DQS		 = 0xC008,
	PIN_MCU_OSPI0_CSN3		 = 0xC03C,
	PIN_MCU_OSPI0_CSN2		 = 0xC038,
	PIN_MCU_OSPI1_CLK		 = 0xC040,
	PIN_MCU_OSPI1_CSN0		 = 0xC05C,
	PIN_MCU_OSPI1_D0		 = 0xC04C,
	PIN_MCU_OSPI1_D1		 = 0xC050,
	PIN_MCU_OSPI1_D2		 = 0xC054,
	PIN_MCU_OSPI1_D3		 = 0xC058,
	PIN_MCU_OSPI1_DQS		 = 0xC048,
	PIN_MCU_OSPI1_LBCLKO		 = 0xC044,
	PIN_WKUP_GPIO0_14		 = 0xC0F8,
	PIN_WKUP_GPIO0_15		 = 0xC0FC,
	PIN_WKUP_GPIO0_13		 = 0xC0F4,
	PIN_WKUP_GPIO0_12		 = 0xC0F0,
	PIN_WKUP_GPIO0_0		 = 0xC0C0,
	PIN_WKUP_GPIO0_1		 = 0xC0C4,
	PIN_WKUP_GPIO0_2		 = 0xC0C8,
	PIN_WKUP_GPIO0_3		 = 0xC0CC,
	PIN_WKUP_GPIO0_6		 = 0xC0D8,
	PIN_WKUP_GPIO0_7		 = 0xC0DC,
	PIN_MCU_OSPI1_CSN1		 = 0xC060,
	PIN_WKUP_GPIO0_49		 = 0xC190,
	PIN_MCU_SPI0_D0		 = 0xC0A4,
	PIN_WKUP_GPIO0_56		 = 0xC120,
	PIN_MCU_SPI0_D1		 = 0xC0A8,
	PIN_MCU_SPI0_CS0		 = 0xC0AC,
	PIN_WKUP_I2C0_SCL		 = 0xC100,
	PIN_WKUP_I2C0_SDA		 = 0xC104,
	PIN_WKUP_GPIO0_67		 = 0xC184,
	PIN_MCU_RESETSTATZ		 = 0xC11C,
	PIN_MCU_RESETZ		 = 0xC118,
	PIN_MCU_SAFETY_ERRORN		 = 0xC114,
	PIN_PMIC_POWER_EN1		 = 0xC110,
	PIN_PORZ		 = 0xC178,
	PIN_RESET_REQZ		 = 0xC174,
	PIN_WKUP_UART0_RXD		 = 0xC0B0,
	PIN_WKUP_UART0_TXD		 = 0xC0B4,
};

/* ========================================================================== */
/*                            Global Variables                                */
/* ========================================================================== */

/** \brief Pinmux configuration data for the board. Auto-generated from 
           Pinmux tool. */
extern pinmuxBoardCfg_t gJ7AEP_MainPinmuxData[];
extern pinmuxBoardCfg_t gJ7AEP_WkupPinmuxData[];

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* _J7AEP_PIN_MUX_H_ */
